### ISSUE TITLE
error compiling library using "CTR" parameter

### ISSUE THREAD

**Issue by barguzar** [angelsl/libncgc#4]
Hi, 

trying to compile the library I got an error. I am using the CTR parameter like the Makefile of "NTRBOOT_FLASHER"
![image](https://user-images.githubusercontent.com/23083925/33137003-580c224a-cf6c-11e7-8634-56d8b92c9485.png)

**Comment by angelsl** [comment]
What version of `make` are you using?

`make -v`

**Comment by barguzar** [comment]
![image](https://user-images.githubusercontent.com/23083925/33140267-18982948-cf75-11e7-9fcd-76f0cd3181fe.png)

**Comment by angelsl** [comment]
Oh boy.

Please use a more recent make. (`undefine` was added in make 3.82)

I suggest you use [MSYS2](http://www.msys2.org/).
